# Generated by Django 4.2.4 on 2023-10-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.AddField(
            model_name='alert',
            name='batch_no',
            field=models.CharField(default='true', max_length=200),
        ),
        migrations.AddField(
            model_name='alert',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
